### ISSUE TITLE
Kemono Support!

### ISSUE THREAD

**Issue by Asurey** [M-rcus/yiff-dl#14]
How possible it is to support kemono.party as well as yiff?

**Comment by M-rcus** [comment]
It's probably possible, but it's most likely not something I wanna support with _this specific_ software.

I feel that's better suited for a separate project, since it's a completely different website.
I'll leave this issue open for the time being while I consider it.

Unfortunately I haven't had much motivation for working on this recently and I highly doubt I personally want to put in effort on supporting another website for this project due to that.

**Comment by Asurey** [comment]
Understandable, take your time.
I would certainly would love to be of help but my coding knowledge it's some very basic python.
Don't know if it is appropiate but the least I can do is thank you for the useful program.
I've been using this tool for the past few days and It's been the most solid tool I've used for the site. 
Saved me a lot of time.

**Comment by M-rcus** [comment]
Though I'd follow up and clean up a bit in these issues, now that Yiff is dead.

I found out that a project called [gallery-dl](https://github.com/mikf/gallery-dl) supports Kemono.party, among [many other services](https://github.com/mikf/gallery-dl/blob/master/docs/supportedsites.rst).

Not sure if you still need a ripper for Kemono, but thought I'd let you know.

Cheers :)
